import type { HeadingLevel } from '../outline/model'

// Shared by the live preview and standalone prototype. A regression test keeps
// these labels in sync with test/vault/heading-level-sample.md.
export const SAMPLE_HEADINGS: ReadonlyArray<readonly [HeadingLevel, string]> = [
  [1, 'h1. Harbor House Community Knowledge Hub'],
  [2, 'h2. Executive summary'],
  [3, 'h3. The opportunity'],
  [3, 'h3. The proposed pilot'],
  [4, 'h4. What success looks like after twelve weeks'],
  [5, 'h5. Weekly signals worth watching'],
  [6, 'h6. A note about misleading early numbers'],
  [2, 'h2. People and responsibilities'],
  [3, 'h3. Resident teacher'],
  [4, 'h4. Before the session'],
  [4, 'h4. During the session'],
  [5, 'h5. Facilitation prompts'],
  [6, 'h6. Safety boundary'],
  [3, 'h3. Session facilitator'],
  [4, "h4. The facilitator's most important job is translating expert shortcuts into steps a first-time learner can actually follow"],
  [3, 'h3. Documentation steward'],
  [4, 'h4. Definition of ready for review'],
  [5, 'h5. Editorial principle'],
  [6, 'h6. Example'],
  [1, 'h1. Program experience'],
  [2, 'h2. Before someone arrives'],
  [3, 'h3. Invitation language'],
  [4, 'h4. Useful invitation'],
  [4, 'h4. Invitation to avoid'],
  [3, 'h3. Accessibility preparation'],
  [5, 'h5. Skipped-level test for an accessibility escalation path'],
  [6, 'h6. Same-day accommodation request'],
  [2, 'h2. During the session'],
  [3, 'h3. Opening ritual'],
  [3, 'h3. Practice cycle'],
  [4, 'h4. Recovery when the demonstration fails'],
  [5, 'h5. Conditions for continuing'],
  [6, 'h6. Incident note'],
  [2, 'h2. After the session'],
  [3, 'h3. Publishing workflow'],
  [4, 'h4. Versioning convention'],
  [1, 'h1. Operations and governance'],
  [2, 'h2. Content boundaries'],
  [3, 'h3. Review levels'],
  [4, 'h4. When classification is uncertain'],
  [3, 'h3. Decision log'],
  [4, 'h4. Example decision'],
  [5, 'h5. Review trigger'],
  [6, 'h6. Evidence to collect'],
  [2, 'h2. Twelve-week learning agenda'],
  [3, 'h3. Questions about participation'],
  [3, 'h3. Questions about usefulness'],
  [4, 'h4. End-of-pilot decision'],
  [1, 'h1. Appendix for visual testing'],
  [2, 'h2. Duplicate labels under different parents'],
  [3, 'h3. Status'],
  [3, 'h3. Status'],
  [2, 'h2. Character coverage'],
  [3, 'h3. Unicode and punctuation'],
  [4, 'h4. A deliberately long heading label for checking wrapping truncation padding arrow alignment and horizontal containment at narrow sidebar widths'],
  [5, 'h5. Narrow sidebar check'],
  [6, 'h6. Final observation'],
]
